[[snippets]]
  description = "show all"
  command = "ls -al"
  output = ""

[[snippets]]
  description = "ping"
  command = "ping 8.8.8.8"
  tag = ["network", "google"]
  output = ""

[[snippets]]
  description = "filer"
  command = "find . -type d -name '.git' -prune -o -type f -print"
  tag = ["filer"]
  output = ""

[[snippets]]
  description = "python-step-count"
  command = 'find . -type d \( -name ".git" -o -name ".venv" -o -name ".mypy_cache" \) -prune -o -type f -print| xargs wc -l'
  tag = ["filer"]
  output = ""

[[snippets]]
  description = "go-step-count"
  command = "find . -name '*.go'| xargs wc -l"
  tag = ["filer"]
  output = ""

[[snippets]]
  description = "display specified field"
  command = "ls -al |awk '{print $1,$9}'"
  tag = ["awk"]
  output = ""

[[snippets]]
  description = "GOPATH mode"
  command = "set --export GO111MODULE off"
  tag = ["go"]
  output = ""

[[snippets]]
  description = "set proxy and discard the response"
  command = "curl -v --proxy http://{adress}:{port} -o /dev/null https://www.google.com"
  tag = ["go"]
  output = ""

[[snippets]]
  description = "print the process listening on 8888"
  command = "lsof -i -P | grep 8888"
  tag = ["network"]
  output = ""
