memodir = "~/go/src/github.com/shuntaka9576/memo"
editor = "nvim"
column = 20
width = 0
selectcmd = 'find ~/go/src/github.com/shuntaka9576/memo -type f |grep -v "/\.git/" |sed -e "s|$HOME/go/src/github.com/shuntaka9576/memo/||g" |fzf'
grepcmd = "grep -nH ${PATTERN} ${FILES}"
memotemplate = ""
assetsdir = "."
pluginsdir = "~/.config/memo/plugins"
templatedirfile = ""
templatebodyfile = ""
