[pet]
src.github = "knqyf263/pet"
fetch.github = "knqyf263/pet"

[memo]
src.github = "mattn/memo"
fetch.github = "mattn/memo"

[fd]
src.github = "sharkdp/fd"
fetch.github = "sharkdp/fd"

[vhs]
src.github = "charmbracelet/vhs"
fetch.github = "charmbracelet/vhs"

[television]
src.github = "alexpasmantier/television"
fetch.github = "alexpasmantier/television"
