# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  agentoast = {
    pname = "agentoast";
    version = "v0.51.0";
    src = fetchFromGitHub {
      owner = "shuntaka9576";
      repo = "agentoast";
      rev = "v0.51.0";
      fetchSubmodules = false;
      sha256 = "sha256-mB5z8Xg6fnARvU3NxKIAYXLsQwmijIRp+kwvgrpumTY=";
    };
  };
  anthropic-skills = {
    pname = "anthropic-skills";
    version = "33375500bcea98d610eb30ce10ac4e59b89c390d";
    src = fetchFromGitHub {
      owner = "anthropics";
      repo = "skills";
      rev = "33375500bcea98d610eb30ce10ac4e59b89c390d";
      fetchSubmodules = false;
      sha256 = "sha256-xUs7UX8pOcZwR0okaSbI/f8EE5F4Zi/BUd+nIZNafPc=";
    };
    date = "2026-09-24";
  };
  gh-infra = {
    pname = "gh-infra";
    version = "d3f874dd62d1f90cfb3f475673e0bfcb02be7ff6";
    src = fetchFromGitHub {
      owner = "babarot";
      repo = "gh-infra";
      rev = "d3f874dd62d1f90cfb3f475673e0bfcb02be7ff6";
      fetchSubmodules = false;
      sha256 = "sha256-imn/EyIWkMs0lVpoLmM/3KYjRWZpNFy+L471oRV7NAs=";
    };
    date = "2026-05-20";
  };
  google-workspace-cli = {
    pname = "google-workspace-cli";
    version = "v0.22.5";
    src = fetchFromGitHub {
      owner = "googleworkspace";
      repo = "cli";
      rev = "v0.22.5";
      fetchSubmodules = false;
      sha256 = "sha256-Bj4gPklufU6p2JpvN6j7QViv7ghSn52jemeXPVXkhlk=";
    };
  };
  memo = {
    pname = "memo";
    version = "v0.0.22";
    src = fetchFromGitHub {
      owner = "mattn";
      repo = "memo";
      rev = "v0.0.22";
      fetchSubmodules = false;
      sha256 = "sha256-xI7R1meEGF5ZJDQvMgbMIkPVVZ2wSZxVt4KcG8fJQyI=";
    };
  };
  pet = {
    pname = "pet";
    version = "v1.0.1";
    src = fetchFromGitHub {
      owner = "knqyf263";
      repo = "pet";
      rev = "v1.0.1";
      fetchSubmodules = false;
      sha256 = "sha256-B0ilobUlp6UUXu6+lVqIHkbFnxVu33eXZFf+F7ODoQU=";
    };
  };
  playwright-cli = {
    pname = "playwright-cli";
    version = "v0.1.21";
    src = fetchFromGitHub {
      owner = "microsoft";
      repo = "playwright-cli";
      rev = "v0.1.21";
      fetchSubmodules = false;
      sha256 = "sha256-ZHfQBZQejJKNYfhszd99i4GIzEpomBzX0/HkMK2T8DQ=";
    };
  };
  worktrunk = {
    pname = "worktrunk";
    version = "v0.79.0";
    src = fetchFromGitHub {
      owner = "max-sixty";
      repo = "worktrunk";
      rev = "v0.79.0";
      fetchSubmodules = false;
      sha256 = "sha256-wOTNqyBd+qw+fREbY52BKtBod0Y50OHRKdHAGljXNuc=";
    };
  };
  zenn-markdown-skill = {
    pname = "zenn-markdown-skill";
    version = "v0.1.0";
    src = fetchFromGitHub {
      owner = "shuntaka9576";
      repo = "zenn-markdown-skill";
      rev = "v0.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-IGVJ/b9QfnFggSYc3RbpUG+UQnP+FiNqfmMqJQww1XY=";
    };
  };
}
