# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  agentoast = {
    pname = "agentoast";
    version = "v0.49.6";
    src = fetchFromGitHub {
      owner = "shuntaka9576";
      repo = "agentoast";
      rev = "v0.49.6";
      fetchSubmodules = false;
      sha256 = "sha256-RqPpMT+qY8GiprcrEmq6wT73GTCjEmhUYShn8uG51BA=";
    };
  };
  anthropic-skills = {
    pname = "anthropic-skills";
    version = "57546260929473d4e0d1c1bb75297be2fdfa1949";
    src = fetchFromGitHub {
      owner = "anthropics";
      repo = "skills";
      rev = "57546260929473d4e0d1c1bb75297be2fdfa1949";
      fetchSubmodules = false;
      sha256 = "sha256-1D9otXxDvmKASBu/vtAEWv6kE+U+jG4OxZpRLZbGEF0=";
    };
    date = "2026-06-09";
  };
  fd = {
    pname = "fd";
    version = "v10.4.2";
    src = fetchFromGitHub {
      owner = "sharkdp";
      repo = "fd";
      rev = "v10.4.2";
      fetchSubmodules = false;
      sha256 = "sha256-D1FCry69KqXgLxU4rVmgKjkM3JqeBRQDfbp3sJtVAbU=";
    };
  };
  gh-infra = {
    pname = "gh-infra";
    version = "d3f874dd62d1f90cfb3f475673e0bfcb02be7ff6";
    src = fetchFromGitHub {
      owner = "babarot";
      repo = "gh-infra";
      rev = "d3f874dd62d1f90cfb3f475673e0bfcb02be7ff6";
      fetchSubmodules = false;
      sha256 = "sha256-imn/EyIWkMs0lVpoLmM/3KYjRWZpNFy+L471oRV7NAs=";
    };
    date = "2026-05-20";
  };
  google-workspace-cli = {
    pname = "google-workspace-cli";
    version = "v0.22.5";
    src = fetchFromGitHub {
      owner = "googleworkspace";
      repo = "cli";
      rev = "v0.22.5";
      fetchSubmodules = false;
      sha256 = "sha256-Bj4gPklufU6p2JpvN6j7QViv7ghSn52jemeXPVXkhlk=";
    };
  };
  memo = {
    pname = "memo";
    version = "v0.0.22";
    src = fetchFromGitHub {
      owner = "mattn";
      repo = "memo";
      rev = "v0.0.22";
      fetchSubmodules = false;
      sha256 = "sha256-xI7R1meEGF5ZJDQvMgbMIkPVVZ2wSZxVt4KcG8fJQyI=";
    };
  };
  pet = {
    pname = "pet";
    version = "v1.0.1";
    src = fetchFromGitHub {
      owner = "knqyf263";
      repo = "pet";
      rev = "v1.0.1";
      fetchSubmodules = false;
      sha256 = "sha256-B0ilobUlp6UUXu6+lVqIHkbFnxVu33eXZFf+F7ODoQU=";
    };
  };
  playwright-cli = {
    pname = "playwright-cli";
    version = "v0.1.14";
    src = fetchFromGitHub {
      owner = "microsoft";
      repo = "playwright-cli";
      rev = "v0.1.14";
      fetchSubmodules = false;
      sha256 = "sha256-wLE04sfPMh43IzIp6/HKBjloy3iSSanSYdYtklc6lQ4=";
    };
  };
  television = {
    pname = "television";
    version = "0.15.9";
    src = fetchFromGitHub {
      owner = "alexpasmantier";
      repo = "television";
      rev = "0.15.9";
      fetchSubmodules = false;
      sha256 = "sha256-JrQUFlhAAaB+VGP184I44hSsIyfCaTMNXxyPp0E5GM0=";
    };
  };
  worktrunk = {
    pname = "worktrunk";
    version = "v0.60.0";
    src = fetchFromGitHub {
      owner = "max-sixty";
      repo = "worktrunk";
      rev = "v0.60.0";
      fetchSubmodules = false;
      sha256 = "sha256-8GmyAx6+sItB/QMZ2GIafavwPVfTldrupJuMMXYSigg=";
    };
  };
  zenn-markdown-skill = {
    pname = "zenn-markdown-skill";
    version = "v0.1.0";
    src = fetchFromGitHub {
      owner = "shuntaka9576";
      repo = "zenn-markdown-skill";
      rev = "v0.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-IGVJ/b9QfnFggSYc3RbpUG+UQnP+FiNqfmMqJQww1XY=";
    };
  };
}
