# =*=*=*=*=*=*=*=*=*=*=*=*=*= package manager *=*=*=*=*=*=*=*=*=*=*=*=*=*=
[[plugins]]
repo = 'Shougo/dein.vim'



# =*=*=*=*=*=*=*=*=*=*=*=*=*= LSP plugins *=*=*=*=*=*=*=*=*=*=*=*=*=*=
[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

# =*=*=*=*=*=*=*=*=*=*=*=*=*= UI plugins *=*=*=*=*=*=*=*=*=*=*=*=*=*=
[[plugins]]
repo='scrooloose/nerdtree'
hook_add = '''
    let NERDTreeShowHidden = 1
'''

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'
hook_add = '''
    " トグル設定
    map <C-e> <plug>NERDTreeTabsToggle<CR>
    " 起動時有効
    let g:nerdtree_tabs_open_on_console_startup=1
    " 起動時にファイルにカーソルを合わせる
    function! s:MoveCursorAtStart()
        call feedkeys("\<C-l>")
    endfunction
    autocmd VimEnter * NERDTree | call s:MoveCursorAtStart()
'''
depends = ['nerdtree']

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
    if has('unix')
        set t_Co=256
        let &t_AB="\e[48;5;%dm"
        let &t_AF="\e[38;5;%dm"
    endif

    " タブラインの表示
    let g:airline#extensions#tabline#enabled = 1
    " （タブが一個の場合）バッファのリストをタブラインに表示する機能をオフ
    let g:airline#extensions#tabline#show_buffers = 0
    " 0でそのタブで開いてるウィンドウ数、1で左のタブから連番
    let g:airline#extensions#tabline#tab_nr_type = 1
    " パワーラインフォントの使用
    let g:airline_powerline_fonts = 1
    " aleの表示
    let g:airline#extensions#ale#enabled = 1
    " Do not collapse the status line while having multiple windows
    let g:airline_inactive_collapse = 0
    " tagbarの表示
    let g:airline#extensions#tagbar#enabled = 1
    " virtualenvを有効
    let g:airline#extensions#virtualenv#enabled = 1
'''

[[plugins]]
repo = 'morhetz/gruvbox'
hook_add = '''
    colorscheme gruvbox

    set background=dark
    set t_Co=256            " gruvboxをカラースキーマにするときに必要！
    let g:ligthline = { 'colorscheme': 'gruvbox' }
'''


# =*=*=*=*=*=*=*=*=*=*=*=*=*= search plugins *=*=*=*=*=*=*=*=*=*=*=*=*=*=
[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
    source ~/dotfiles/nvim/plugins/denite.vim
'''
