[[plugins]]
repo='scrooloose/nerdtree'
hook_add = '''
    let NERDTreeShowHidden = 1
'''

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'
hook_add = '''
    map <C-e> <plug>NERDTreeTabsToggle<CR>

    " Don't display the NERDTree when specifying files
    autocmd StdinReadPre * let s:std_in=1
    autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
'''
depends = ['nerdtree']

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
    if has('unix')
        set t_Co=256
        let &t_AB="\e[48;5;%dm"
        let &t_AF="\e[38;5;%dm"
    endif

    let g:airline#extensions#tabline#enabled = 1
    let g:airline#extensions#tabline#show_buffers = 0
    let g:airline#extensions#tabline#tab_nr_type = 1
    let g:airline_powerline_fonts = 1
    let g:airline#extensions#ale#enabled = 1
    " Do not collapse the status line while having multiple windows
    let g:airline_inactive_collapse = 0
    let g:airline#extensions#tagbar#enabled = 1
    let g:airline#extensions#virtualenv#enabled = 1
'''

[[plugins]]
repo = 'morhetz/gruvbox'
hook_add = '''
    colorscheme gruvbox

    set background=dark
    set t_Co=256
    let g:ligthline = { 'colorscheme': 'gruvbox' }
'''

[[plugins]]
repo = 'christoomey/vim-tmux-navigator'
hook_add = '''
    let g:tmux_navigator_no_mappings = 1

    nnoremap <silent> <C-w>j :TmuxNavigateDown<CR>
    nnoremap <silent> <C-w>h :TmuxNavigateLeft<CR>
    nnoremap <silent> <C-w>k :TmuxNavigateUp<CR>
    nnoremap <silent> <C-w>l :TmuxNavigateRight<CR>
    nnoremap <silent> <C-w>\\ :TmuxNavigatePrevious<CR>
'''
