[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'thinca/vim-quickrun'
depends = ['vimproc.vim']
on_ft = ['python', 'go']
hook_source = '''
  source ~/dotfiles/nvim/plugins/quickrun.vim
'''

[[plugins]]
repo = 'w0rp/ale'
on_ft = ['go', 'python', 'json', 'make', 'vim', 'shell']
hook_source = '''
    source ~/dotfiles/nvim/plugins/ale.vim
'''

[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
on_ft = ['python', 'go']
depends = ['async.vim']
hook_source = '''
    source ~/dotfiles/nvim/plugins/lsp.vim
'''
