# ======================================================================================================================
# Package manager
# ======================================================================================================================
[[plugins]]
repo = 'Shougo/dein.vim'

# ======================================================================================================================
# LSP
# ======================================================================================================================
[[plugins]]
repo = 'neoclide/coc.nvim'
merged = 0
build = 'yarn install --frozen-lockfile'
hook_add = '''
source ~/dotfiles/nvim/plugins/coc.vim
'''

[[plugins]]
repo = "airblade/vim-gitgutter"
hook_add = '''
let g:gitgutter_map_keys = 0
nmap [g <Plug>GitGutterPrevHunk
nmap ]g <Plug>GitGutterNextHunk
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
syntax on

let g:lightline = {
      \ 'colorscheme': 'PaperColor_dark',
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'cocstatus', 'currentfunction', 'readonly', 'filepath', 'modified' ] ]
      \ },
      \ 'component_function': {
      \   'cocstatus': 'coc#status',
      \   'currentfunction': 'CocCurrentFunction',
      \   'filepath': 'FilePath',
      \   'filetype': 'MyFiletype',
      \   'fileformat': 'MyFileformat'
      \ },
      \ }

function! CocCurrentFunction()
  return get(b:, 'coc_current_function', '')
endfunction

function! FilePath()
  let fullpath = substitute(expand('%:p'), $HOME, '~', '')
  return fullpath
endfunction

" # show statusbar
set laststatus=2
" # hide --INSERT--
set noshowmode
'''
hook_post_source = '''
function! MyFiletype()
  return winwidth(0) > 70 ? (strlen(&filetype) ? &filetype . ' ' . WebDevIconsGetFileTypeSymbol() : 'no ft') : ''
endfunction

function! MyFileformat()
  return winwidth(0) > 70 ? (&fileformat . ' ' . WebDevIconsGetFileFormatSymbol()) : ''
endfunction
'''

[[plugins]]
repo='simeji/winresizer.git'

[[plugins]]
repo = 'christoomey/vim-tmux-navigator'
hook_add = '''
let g:tmux_navigator_no_mappings = 1

nnoremap <silent> <C-w>j :TmuxNavigateDown<CR>
nnoremap <silent> <C-w>h :TmuxNavigateLeft<CR>
nnoremap <silent> <C-w>k :TmuxNavigateUp<CR>
nnoremap <silent> <C-w>l :TmuxNavigateRight<CR>
nnoremap <silent> <C-w>\\ :TmuxNavigatePrevious<CR>
'''

# ======================================================================================================================
# Color schema settings
# ======================================================================================================================
[[plugins]]
repo = 'joshdick/onedark.vim'
hook_add='''
colorscheme onedark
'''

# ======================================================================================================================
# easy-motion
# ======================================================================================================================
[[plugins]]
repo='haya14busa/incsearch.vim'
hook_source = '''
set hlsearch
let g:incsearch#auto_nohlsearch = 1

map n  <Plug>(incsearch-nohl-n)
map N  <Plug>(incsearch-nohl-N)
map *  <Plug>(incsearch-nohl-*)
'''

[[plugins]]
repo='haya14busa/incsearch-easymotion.vim'
depends = ['incsearch.vim', 'easymotion/vim-easymotion']
hook_add = '''
map z/ <Plug>(incsearch-easymotion-/)
map z? <Plug>(incsearch-easymotion-?)
map zg/ <Plug>(incsearch-easymotion-stay)
'''

[[plugins]]
repo='easymotion/vim-easymotion'
hook_add = '''
" japanise move
let g:EasyMotion_use_migemo = 1

map f <Plug>(easymotion-bd-f)
nmap f <Plug>(easymotion-overwin-f)
nmap s <Plug>(easymotion-overwin-f2)

" Move to line
map L <Plug>(easymotion-bd-jk)
nmap L <Plug>(easymotion-overwin-line)

" Move to word
map  w <Plug>(easymotion-bd-w)
nmap w <Plug>(easymotion-overwin-w)

" You can use other keymappings like <C-l> instead of <CR> if you want to
" use these mappings as default search and sometimes want to move cursor with
" EasyMotion.
function! s:incsearch_config(...) abort
  return incsearch#util#deepextend(deepcopy({
        \ 'modules': [incsearch#config#easymotion#module({'overwin': 1})],
        \ 'keymap': {
        \   '\<CR>': '<Over>(easymotion)'
        \ },
        \   'is_expr': 0
        \ }), get(a:, 1, {}))
endfunction

noremap <silent><expr> /  incsearch#go(<SID>incsearch_config())
noremap <silent><expr> ?  incsearch#go(<SID>incsearch_config({'command': '?'}))
noremap <silent><expr> g/ incsearch#go(<SID>incsearch_config({'is_stay': 1}))
'''

# ======================================================================================================================
# Replace characters
# ======================================================================================================================
[[plugins]]
repo = 'kana/vim-operator-replace'
hook_add= '''
map R  <Plug>(operator-replace)
'''

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'osyo-manga/vim-over'
hook_add='''
nnoremap <silent> <Leader>m :OverCommandLine<CR>
nnoremap sub :OverCommandLine<CR>%s/<C-r><C-w>//g<Left><Left>
nnoremap subp y:OverCommandLine<CR>%s!<C-r>=substitute(@0, '!', '\\!', 'g')<CR>!!gI<Left><Left><Left>
'''

[[plugins]]
repo = 'lambdalisue/fern-renderer-devicons.vim'

[[plugins]]
repo = 'lambdalisue/fern.vim'
depends = ['vim-devicons']
hook_add='''
" アイコン有効化
let g:fern#renderer = "devicons"
let g:fern#default_hidden = 1

" 起動コマンド
nnoremap <silent><Leader>d :<C-u>Fern . -drawer -toggle<CR>
" スタートアップでfernを起動する
augroup my-fern-startup
  autocmd! *
  autocmd VimEnter * ++nested Fern . -drawer
augroup END

" netrwの無効化
let g:loaded_netrw             = 1
let g:loaded_netrwPlugin       = 1
let g:loaded_netrwSettings     = 1
let g:loaded_netrwFileHandlers = 1

augroup my-fern-hijack
  autocmd!
  autocmd BufEnter * ++nested call s:hijack_directory()
augroup END

function! s:hijack_directory() abort
  let path = expand('%:p')
  if !isdirectory(path)
    return
  endif
  bwipeout %
  execute printf('Fern %s', fnameescape(path))
endfunction

nnoremap <silent> <Leader>ee :<C-u>Fern <C-r>=<SID>smart_path()<CR><CR>
function! s:smart_path() abort
  if !empty(&buftype) || bufname('%') =~# '^[^:]\+://'
    return fnamemodify('.', ':p')
  endif
  return fnamemodify(expand('%'), ':p:h')
endfunction

" ?
nmap <buffer><silent> <Plug>(fern-my-open-and-close)
      \ <Plug>(fern-action-open)
      \ :<C-u>FernDo close -drawer -stay<CR>

" コンフィグ設定
function! s:init_fern() abort
  nmap <buffer> <Space> <Plug>(fern-action-mark-toggle)
  nmap <buffer><expr>
      \ <Plug>(fern-my-expand-or-collapse)
      \ fern#smart#leaf(
      \   "\<Plug>(fern-action-collapse)",
      \   "\<Plug>(fern-action-expand)",
      \   "\<Plug>(fern-action-collapse)",
      \ )
  nmap <buffer><nowait> o <Plug>(fern-my-expand-or-collapse)
  nmap <buffer><expr>
        \ <Plug>(fern-my-expand-or-enter)
        \ fern#smart#drawer(
        \   "\<Plug>(fern-open-or-expand)",
        \   "\<Plug>(fern-open-or-enter)",
        \ )
  nmap <buffer><expr>
        \ <Plug>(fern-my-collapse-or-leave)
        \ fern#smart#drawer(
        \   "\<Plug>(fern-action-collapse)",
        \   "\<Plug>(fern-action-leave)",
        \ )
  nmap <buffer><nowait> l <Plug>(fern-action-enter)
  nmap <buffer><nowait> h <Plug>(fern-action-leave)
  nmap <buffer><nowait> e <Plug>(fern-action-open:side)
  nmap <buffer><nowait> d <Plug>(fern-action-remove)
endfunction

augroup fern-custom
  autocmd! *
  autocmd FileType fern call s:init_fern()
augroup END
'''

[[plugins]]
repo = 'lambdalisue/gina.vim'

[[plugins]]
repo = "voldikss/vim-floaterm"
hook_add ='''
let g:floaterm_keymap_new    = '<C-a>N'
let g:floaterm_keymap_prev   = '<C-a><C-p>'
let g:floaterm_keymap_next   = '<C-a><C-n>'
let g:floaterm_keymap_toggle = '<C-a><C-h>'
let g:floaterm_width = 0.9
let g:floaterm_height = 0.9
command! L execute(":FloatermNew") | execute(":FloatermNew! lazygit")
'''

# ======================================================================================================================
# Flutter
# ======================================================================================================================
[[plugins]]
repo = 'dart-lang/dart-vim-plugin'
hook_add='''
let g:dart_style_guide = 2
'''

[[plugins]]
repo = 'thosakwe/vim-flutter'
