# ======================================================================================================================
# Syntax highlight settings
# ======================================================================================================================
[[plugins]]
repo = 'inkarkat/vim-SyntaxRange'

[[plugins]]
repo = 'ryanoasis/vim-devicons'
hook_add = '''
let g:airline_powerline_fonts = 1
let g:WebDevIconsOS = 'Darwin'
let g:WebDevIconsUnicodeDecorateFolderNodes = 1
let g:webdevicons_conceal_nerdtree_brackets = 1
let g:DevIconsEnableFoldersOpenClose = 1
let g:WebDevIconsUnicodeDecorateFolderNodes = 1
let g:DevIconsDefaultFolderOpenSymbol = ''
let g:WebDevIconsUnicodeDecorateFolderNodesDefaultSymbol = ''
'''

[[plugins]]
repo = 'chemzqm/denite-git'

[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
build = ':UpdateRemotePlugins'
depends = ['vim-devicons']
hook_add='''
nmap [denite] <Nop>
map <C-j> [denite]
nnoremap <silent> [denite]<C-p> :<C-u>Denite file/rec<CR>
nnoremap <silent> [denite]<C-i> :<C-u>Denite buffer<CR>
nnoremap <silent> [denite]<C-a> :<C-u>Denite floaterm<CR>
command! D execute(":Denite grep -buffer-name=grep-buffer-denite")
command! Dresume execute(":Denite -resume -buffer-name=grep-buffer-denite")
command! Dnext execute(":Denite -resume -buffer-name=grep-buffer-denite -cursor-pos=+1 -immediately")
command! Dprev execute(":Denite -resume -buffer-name=grep-buffer-denite -cursor-pos=-1 -immediately")
nmap <silent> [denite]<C-m> :<C-u>Denite -resume -buffer-name=grep-buffer-denite<CR>
nnoremap <silent> [denite]n :<C-u>Denite -resume -buffer-name=grep-buffer-denite -cursor-pos=+1 -immediately<CR>
nnoremap <silent> [denite]p :<C-u>Denite -resume -buffer-name=grep-buffer-denite -cursor-pos=-1 -immediately<CR>
'''
hook_source = '''
    source ~/dotfiles/nvim/plugins/denite.vim
    let g:webdevicons_enable_denite = 1
'''

[[plugins]]
repo = "tpope/vim-fugitive"
on_cmd = [
  'Git',
  'Gcommit',
  'Gstatus',
  'Gdiff',
  'Gblame',
  'Glog'
]
hook_add = '''
nmap [figitive] <Nop>
map <Leader>g [figitive]
nnoremap <silent> [figitive]c :<C-u>Gcommit<CR>
nnoremap <silent> [figitive]d :<C-u>Gdiff<CR>
nnoremap <silent> [figitive]b :<C-u>Gblame<CR>
nnoremap <silent> [figitive]l :<C-u>Glog<CR>
'''

# ======================================================================================================================
# Realtime preview plugins settings
# ======================================================================================================================
[[plugins]]
repo = 'shuntaka9576/preview-asciidoc.nvim'
on_ft = ['asciidoc']
build = 'yarn install'
merged = 0

[[plugins]]
repo = 'shuntaka9576/preview-swagger.nvim'
on_ft = ['yaml']
build = 'yarn install'

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
build =  'cd app & yarn install'

# ======================================================================================================================
# Markdown
# ======================================================================================================================
[[plugins]]
repo = 'godlygeek/tabular'
on_ft = ['markdown']

[[plugins]]
repo = 'joker1007/vim-markdown-quote-syntax'
on_ft = ['markdown']

[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown']
hook_add = '''
let g:vim_markdown_better_folding=0
let g:vim_markdown_folding_level = 6
let g:vim_markdown_frontmatter = 1
'''

# ======================================================================================================================
# Python code formatter settings
# ======================================================================================================================
[[plugins]]
repo = 'fisadev/vim-isort'
on_ft = ['python']

[[plugins]]
repo = 'python/black'
on_ft = ['python']
hook_add='''
" autocmd BufWritePost *.py silent execute ':Black'
"  autocmd BufWritePre *.py silent execute ':Black'
'''

# ======================================================================================================================
# Go code formatter settings
# ======================================================================================================================
[[plugins]]
repo='mattn/vim-goimports'
on_ft = ['go']

# ======================================================================================================================
# TypeScript code formatter settings
# ======================================================================================================================

# rust
[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ['rust']
hook_add='''
  let g:rustfmt_autosave = 1
'''

