[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
syntax on

let g:lightline = {
      \ 'colorscheme': 'onedark',
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'cocstatus', 'currentfunction', 'readonly', 'filepath', 'modified' ] ]
      \ },
      \ 'component_function': {
      \   'cocstatus': 'coc#status',
      \   'currentfunction': 'CocCurrentFunction',
      \   'filepath': 'FilePath',
      \   'filetype': 'MyFiletype',
      \   'fileformat': 'MyFileformat'
      \ },
      \ }

function! CocCurrentFunction()
  return get(b:, 'coc_current_function', '')
endfunction

function! FilePath()
  let fullpath = substitute(expand('%:p'), $HOME, '~', '')
  return fullpath
endfunction

" # show statusbar
set laststatus=2
" # hide --INSERT--
set noshowmode
'''
hook_post_source = '''
function! MyFiletype()
  return winwidth(0) > 70 ? (strlen(&filetype) ? &filetype . ' ' . WebDevIconsGetFileTypeSymbol() : 'no ft') : ''
endfunction

function! MyFileformat()
  return winwidth(0) > 70 ? (&fileformat . ' ' . WebDevIconsGetFileFormatSymbol()) : ''
endfunction
'''

[[plugins]]
repo='simeji/winresizer.git'
hook_add='''
" let g:winresizer_start_key = '<C-T>'
'''

 [[plugins]]
 repo = 'joshdick/onedark.vim'
 hook_add = '''
 colorscheme onedark
 '''

[[plugins]]
repo = 'christoomey/vim-tmux-navigator'
hook_add = '''
    let g:tmux_navigator_no_mappings = 1

    nnoremap <silent> <C-w>j :TmuxNavigateDown<CR>
    nnoremap <silent> <C-w>h :TmuxNavigateLeft<CR>
    nnoremap <silent> <C-w>k :TmuxNavigateUp<CR>
    nnoremap <silent> <C-w>l :TmuxNavigateRight<CR>
    nnoremap <silent> <C-w>\\ :TmuxNavigatePrevious<CR>
'''

