[[plugins]]
repo = 'Shougo/defx.nvim'
build = ':UpdateRemotePlugins'
depends = ['defx-git', 'defx-icons']
on_cmd = 'Defx'
hook_add = '''
  nnoremap <silent><Leader>d :<C-u>Defx -split=vertical -winwidth=30 -direction=topleft -ignored-files='.git' -toggle -resume<CR>
  nnoremap <silent><Leader>f :<C-u>Defx -ignored-files='.git' -new `expand('%:p:h')`<CR>
'''
hook_source = '''
  autocmd FileType defx call s:defx_my_settings()
  function! s:defx_my_settings() abort
    " control tree action mappings
    nnoremap <silent><buffer><expr> o
    \ defx#is_directory() ?
    \ defx#do_action('open_or_close_tree') :
    \ defx#do_action('drop')
    nnoremap <silent><buffer><expr> l
    \ defx#do_action('open')
    " control file or directory mappings
    nnoremap <silent><buffer><expr> c
    \ defx#do_action('copy')
    nnoremap <silent><buffer><expr> m
    \ defx#do_action('move')
    nnoremap <silent><buffer><expr> p
    \ defx#do_action('paste')
    nnoremap <silent><buffer><expr> r
    \ defx#do_action('rename')
    nnoremap <silent><buffer><expr> d
    \ defx#do_action('remove')
    nnoremap <silent><buffer><expr> q
    \ defx#do_action('quit')
    nnoremap <silent><buffer><expr> h
    \ defx#do_action('cd', ['..'])
    nnoremap <silent><buffer><expr> <C-l>
    \ defx#do_action('redraw')
    nnoremap <silent><buffer><expr> <C-g>
    \ defx#do_action('print')
    nnoremap <silent><buffer><expr> ~
    \ defx#do_action('cd')
    nnoremap <silent><buffer><expr> cd
    \ defx#do_action('change_vim_cwd')
  endfunction
'''
[[plugins]]
repo = 'kristijanhusak/defx-icons.git'
[[plugins]]
repo = 'kristijanhusak/defx-git'

[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
build = ':UpdateRemotePlugins'
hook_add='''
    let g:python3_host_prog = expand('~/.anyenv/envs/pyenv/shims/python3')
    nmap [denite] <Nop>
    map <C-j> [denite]
    nnoremap <silent> [denite]<C-p> :<C-u>Denite file/rec<CR>
    nnoremap <silent> [denite]<C-i> :<C-u>Denite buffer<CR>
    command! D execute(":Denite grep -buffer-name=grep-buffer-denite")
    command! Dresume execute(":Denite -resume -buffer-name=grep-buffer-denite")
    command! Dnext execute(":Denite -resume -buffer-name=grep-buffer-denite -cursor-pos=+1 -immediately")
    command! Dprev execute(":Denite -resume -buffer-name=grep-buffer-denite -cursor-pos=-1 -immediately")
    nmap <silent> [denite]<C-m> :<C-u>Denite -resume -buffer-name=grep-buffer-denite<CR>
    nnoremap <silent> [denite]n :<C-u>Denite -resume -buffer-name=grep-buffer-denite -cursor-pos=+1 -immediately<CR>
    nnoremap <silent> [denite]p :<C-u>Denite -resume -buffer-name=grep-buffer-denite -cursor-pos=-1 -immediately<CR>
'''
hook_source = '''
    source ~/dotfiles/nvim/plugins/denite.vim
'''

# =*=*=*=*=*=*=*=*=*=*=*=*=*= Run Code *=*=*=*=*=*=*=*=*=*=*=*=*=*
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'thinca/vim-quickrun'
depends = ['vimproc.vim']
on_ft = ['python', 'go', 'julia', 'rust', 'typescript']
hook_source = '''
  source ~/dotfiles/nvim/plugins/quickrun.vim
'''

# =*=*=*=*=*=*=*=*=*=*=*=*=*= Linter *=*=*=*=*=*=*=*=*=*=*=*=*=*
# [[plugins]]
# repo = 'w0rp/ale'
# on_ft = ['go', 'python', 'json', 'make', 'vim', 'shell', 'js', 'vue', 'ts']
# hook_add = '''
#     source ~/dotfiles/nvim/plugins/ale.vim
# '''
