[[plugins]]
repo = 'Shougo/dein.vim'

#[[plugins]]
#repo = 'prabirshrestha/asyncomplete.vim'
#
#[[plugins]]
#repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
    source ~/dotfiles/nvim/plugins/denite.vim
'''

[[plugins]]
repo = 'osyo-manga/vim-over'
hook_add = '''
    nnoremap <silent> <Space>o :OverCommandLine<CR>%s//g<Left><Left>
    vnoremap <silent> <Space>o :OverCommandLine<CR>s//g<Left><Left>
    nnoremap sub :OverCommandLine<CR>%s/<C-r><C-w>//g<Left><Left><Paste>
'''

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'

[[plugins]]
repo = "airblade/vim-gitgutter"
hook_add = '''
    let g:gitgutter_map_keys = 0
    nmap [g <Plug>GitGutterPrevHunk
    nmap ]g <Plug>GitGutterNextHunk
'''

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'neoclide/coc.nvim'
build = 'coc#util#install()'
hook_add = '''
    source ~/dotfiles/nvim/plugins/coc.vim
'''

[[plugins]]
repo = 'junegunn/fzf'

[[plugins]]
repo = 'posva/vim-vue'
on_ft = 'vue'
hook_add = '''
    autocmd FileType vue syntax sync fromstart

    let g:ft = ''
    function! NERDCommenter_before()
      if &ft == 'vue'
        let g:ft = 'vue'
        let stack = synstack(line('.'), col('.'))
        if len(stack) > 0
          let syn = synIDattr((stack)[0], 'name')
          if len(syn) > 0
            exe 'setf ' . substitute(tolower(syn), '^vue_', '', '')
          endif
        endif
      endif
    endfunction
    function! NERDCommenter_after()
      if g:ft == 'vue'
        setf vue
        let g:ft = ''
      endif
    endfunction
'''

#[[plugins]]
#repo = 'Shougo/context_filetype.vim'
#
#[[plugins]]
#repo = "osyo-manga/vim-precious"
